import { useState } from "react";
import { ArrowLeftIcon, ChevronRightIcon, HeartFilledIcon, HeartIcon, MagnifyingGlassIcon, MinusIcon, PlusIcon, Share1Icon, PlayIcon, BookmarkIcon } from "@radix-ui/react-icons";
import { MobileScroll } from "./mobile";

type Page = "home" | "cookbook" | "recipe" | "plan";
type Recipe = { title: string; category: string; cuisine: string; time: string; image: string; favourite?: boolean };
const recipes: Recipe[] = [
  { title: "Smoky Jollof Rice", category: "Main", cuisine: "Ghanaian", time: "35 min", favourite: true, image: "https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=900&q=85" },
  { title: "Lemon Herb Pasta", category: "Main", cuisine: "Italian", time: "20 min", image: "https://images.unsplash.com/photo-1473093295043-cdd812d0e601?auto=format&fit=crop&w=900&q=85" },
  { title: "Cucumber Feta Salad", category: "Salad", cuisine: "Mediterranean", time: "15 min", favourite: true, image: "https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&w=900&q=85" },
  { title: "Raspberry Celebration Cake", category: "Cake & Baking", cuisine: "British", time: "50 min", image: "https://images.unsplash.com/photo-1578985545062-69928b1d9587?auto=format&fit=crop&w=900&q=85" },
];
function RecipeCard({ recipe, onOpen }: { recipe: Recipe; onOpen: () => void }) { return <button className="recipe-card" onClick={onOpen}><img src={recipe.image} alt={recipe.title} /><span className="heart">{recipe.favourite ? <HeartFilledIcon /> : <HeartIcon />}</span><strong>{recipe.title}</strong><small>{recipe.cuisine} · {recipe.category}</small></button>; }
export default function Prototype() {
 const [page, setPage] = useState<Page>("home"), [servings, setServings] = useState(4), [metric, setMetric] = useState(true), [plan, setPlan] = useState<Recipe[]>([recipes[0]]);
 const openRecipe=()=>setPage("recipe"); const addToPlan=(r:Recipe)=>setPlan(p=>p.some(x=>x.title===r.title)?p:[...p,r]);
 if(page==="recipe") return <MobileScroll className="app-screen"><main className="recipe-page"><button className="round-action back" onClick={()=>setPage("cookbook")}><ArrowLeftIcon/></button><button className="round-action share"><Share1Icon/></button><img className="recipe-hero" src={recipes[0].image} alt="Smoky Jollof Rice"/><section className="recipe-sheet"><p className="eyebrow">GHANAIAN · MAIN</p><div className="title-row"><h1>Smoky Jollof Rice</h1><HeartFilledIcon className="favourite"/></div><p className="muted">A vibrant one-pot classic, saved from @KwekuCooks.</p><div className="quick-facts"><span>◷ 35 min</span><span>◉ Easy</span><span>♨ 1 pot</span></div><a className="video-link" href="https://www.youtube.com/" target="_blank" rel="noreferrer"><PlayIcon/> Play original video <ChevronRightIcon/></a><div className="recipe-tools"><div><small>SERVINGS</small><div className="stepper"><button onClick={()=>setServings(Math.max(1,servings-1))}><MinusIcon/></button><strong>{servings}</strong><button onClick={()=>setServings(servings+1)}><PlusIcon/></button></div></div><div className="unit-toggle"><button className={metric?"selected":""} onClick={()=>setMetric(true)}>Metric</button><button className={!metric?"selected":""} onClick={()=>setMetric(false)}>Imperial</button></div></div><h2>Ingredients</h2><ul className="ingredients"><li><span>☐</span>{metric?`${Math.round(400*servings/4)}g`:`${(14.1*servings/4).toFixed(1)} oz`} long-grain rice</li><li><span>☐</span>{metric?`${Math.round(500*servings/4)}ml`:`${(2.1*servings/4).toFixed(1)} cups`} chicken stock</li><li><span>☐</span>{Math.round(2*servings/4)} red peppers</li><li><span>☐</span>{Math.round(4*servings/4)} chicken thighs</li></ul><h2>Method</h2><ol className="method"><li>Blend the peppers, tomatoes and onion until smooth.</li><li>Simmer the sauce with spices for 10 minutes.</li><li>Stir in rice and stock. Cover and cook until tender.</li></ol><button className="primary full" onClick={()=>{addToPlan(recipes[0]);setPage("plan")}}>Add to meal plan <PlusIcon/></button></section></main><nav className="bottom-nav"><button onClick={()=>setPage("home")}>⌂<span>Home</span></button><button onClick={()=>setPage("cookbook")}>▣<span>Cookbook</span></button><button className="add-nav" onClick={()=>setPage("cookbook")}><PlusIcon/></button><button onClick={()=>setPage("plan")}>□<span>Plan</span></button><button>♙<span>Profile</span></button></nav></MobileScroll>;
 const nav=<nav className="bottom-nav"><button className={page==="home"?"active":""} onClick={()=>setPage("home")}>⌂<span>Home</span></button><button className={page==="cookbook"?"active":""} onClick={()=>setPage("cookbook")}>▣<span>Cookbook</span></button><button className="add-nav" onClick={()=>setPage("cookbook")}><PlusIcon/></button><button className={page==="plan"?"active":""} onClick={()=>setPage("plan")}>□<span>Plan</span></button><button>♙<span>Profile</span></button></nav>;
 if(page==="cookbook") return <MobileScroll className="app-screen"><main className="screen-content"><header className="app-header"><div><p className="brand">Savorly</p><h1>Your cookbook</h1></div><button className="coral-circle"><PlusIcon/></button></header><label className="search"><MagnifyingGlassIcon/><input placeholder="Search recipes"/></label><div className="filter-row"><button className="chip selected">All</button><button className="chip">Mains</button><button className="chip">Drinks</button><button className="chip">Cakes</button></div><div className="sort-row"><span>24 recipes</span><button>Recently added ▾</button></div><section className="recipe-grid">{recipes.map(r=><RecipeCard key={r.title} recipe={r} onOpen={openRecipe}/>)}</section></main>{nav}</MobileScroll>;
 if(page==="plan") return <MobileScroll className="app-screen"><main className="screen-content plan"><header className="app-header"><div><p className="brand">Savorly</p><h1>Meal plan</h1></div><button className="round-action"><Share1Icon/></button></header><div className="week"><button>‹</button><strong>6 – 12 October</strong><button>›</button></div><section className="calendar"><div className="calendar-head"><span>Mon</span><span>Tue</span><span>Wed</span><span>Thu</span><span>Fri</span><span>Sat</span><span>Sun</span></div><div className="calendar-days">{[6,7,8,9,10,11,12].map((day,index)=><button key={day} className={index===0?"calendar-day selected-day":"calendar-day"}><span>{day}</span>{index===0?<b>Jollof</b>:index===2?<i>+</i>:null}</button>)}</div></section><section className="plan-day"><p>MONDAY · 6 OCT</p>{plan.map(r=><div className="plan-recipe" key={r.title}><img src={r.image} alt=""/><div><strong>{r.title}</strong><small>{r.time} · {r.category}</small></div><BookmarkIcon/></div>)}<button className="add-meal" onClick={()=>addToPlan(recipes[1])}><PlusIcon/> Add another recipe</button></section><section className="plan-day muted-day"><p>WEDNESDAY · 8 OCT</p><button className="add-meal" onClick={()=>addToPlan(recipes[2])}><PlusIcon/> Add a recipe</button></section><button className="primary full"><BookmarkIcon/> Create shopping list</button></main>{nav}</MobileScroll>;
 return <MobileScroll className="app-screen"><main className="screen-content"><header className="app-header"><div><p className="brand">Savorly</p><h1>Your kitchen</h1></div><button className="primary small" onClick={()=>setPage("cookbook")}><PlusIcon/> Add recipe</button></header><label className="search"><MagnifyingGlassIcon/><input placeholder="Search your recipes..."/></label><section className="category-grid"><button onClick={()=>setPage("cookbook")} className="category main-cat"><span>Mains</span></button><button onClick={()=>setPage("cookbook")} className="category drinks-cat"><span>Drinks</span></button><button onClick={()=>setPage("cookbook")} className="category cakes-cat"><span>Cakes & Baking</span></button><button onClick={()=>setPage("cookbook")} className="category salad-cat"><span>Salads</span></button></section><div className="section-heading"><h2>Saved from video</h2><button onClick={()=>setPage("cookbook")}>See all <ChevronRightIcon/></button></div><button className="video-card" onClick={openRecipe}><img src={recipes[0].image} alt="Jollof rice"/><div><p className="source"><PlayIcon/> From video</p><h3>Smoky Jollof Rice</h3><p>Ghanaian classic, made simple.</p><small>◷ 35 mins · 4 servings</small><span className="review">Review recipe <ChevronRightIcon/></span></div></button></main>{nav}</MobileScroll>;
}
