import { useMemo, useState } from "react";
import { ArrowLeftIcon, CheckIcon, ChevronRightIcon, HeartFilledIcon, HeartIcon, MagnifyingGlassIcon, MinusIcon, PlusIcon, PlayIcon, Share1Icon } from "@radix-ui/react-icons";
import { BottomSheet, KeyboardInput, KeyboardTextarea, MobileScroll, useKeyboard } from "./mobile";

type Route = "home" | "cookbook" | "recipe" | "plan";
type Evidence = "from-video" | "estimated" | "not-stated";
type Ingredient = { id: string; name: string; quantity?: number; unit?: "g" | "ml" | "piece"; evidence: Evidence };
type Recipe = { id: string; title: string; category: string; cuisine: string; time: string; image: string; sourceUrl: string; servings: number; favourite: boolean; manualOrder?: number; ingredients: Ingredient[]; method: string[] };
type Data = { version: 1; recipes: Recipe[]; mealPlan: { id: string; recipeId: string; date: string }[] };
const image = { jollof:"https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=900&q=85", pasta:"https://images.unsplash.com/photo-1473093295043-cdd812d0e601?auto=format&fit=crop&w=900&q=85", salad:"https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&w=900&q=85", cake:"https://images.unsplash.com/photo-1578985545062-69928b1d9587?auto=format&fit=crop&w=900&q=85" };
const seed: Recipe[] = [
  {id:"jollof",title:"Smoky Jollof Rice",category:"Main",cuisine:"Ghanaian",time:"35 min",image:image.jollof,sourceUrl:"https://www.youtube.com/",servings:4,favourite:true,manualOrder:0,ingredients:[{id:"rice",name:"long-grain rice",quantity:400,unit:"g",evidence:"from-video"},{id:"stock",name:"chicken stock",quantity:500,unit:"ml",evidence:"estimated"},{id:"pepper",name:"red peppers",quantity:2,unit:"piece",evidence:"from-video"}],method:["Blend peppers, tomatoes and onion until smooth.","Simmer sauce with spices for 10 minutes.","Stir in rice and stock. Cover and cook until tender."]},
  {id:"pasta",title:"Lemon Herb Pasta",category:"Main",cuisine:"Italian",time:"20 min",image:image.pasta,sourceUrl:"https://www.youtube.com/",servings:2,favourite:false,ingredients:[{id:"pasta",name:"pasta",quantity:250,unit:"g",evidence:"from-video"}],method:["Cook pasta.","Toss with lemon and herbs."]},
  {id:"salad",title:"Cucumber Feta Salad",category:"Salad",cuisine:"Mediterranean",time:"15 min",image:image.salad,sourceUrl:"https://www.instagram.com/",servings:2,favourite:true,manualOrder:1,ingredients:[{id:"cucumber",name:"cucumber",quantity:2,unit:"piece",evidence:"from-video"}],method:["Slice vegetables.","Dress and finish with feta."]},
  {id:"cake",title:"Raspberry Celebration Cake",category:"Cake & Baking",cuisine:"British",time:"50 min",image:image.cake,sourceUrl:"https://www.tiktok.com/",servings:8,favourite:false,ingredients:[{id:"flour",name:"flour",quantity:300,unit:"g",evidence:"estimated"}],method:["Whisk batter.","Bake until springy."]}
];
const key="savorly-data-v1";
const load=():Data=>{try{const raw=localStorage.getItem(key);const value=raw?JSON.parse(raw) as Data:null;return value?.version===1?value:{version:1,recipes:seed,mealPlan:[{id:"seed-plan",recipeId:"jollof",date:"2026-10-06"}]};}catch{return {version:1,recipes:seed,mealPlan:[]};}};
const scale=(n:number|undefined,from:number,to:number)=>n===undefined?undefined:n*to/from;
const quantity=(item:Ingredient,from:number,to:number,imperial:boolean)=>{const n=scale(item.quantity,from,to);if(n===undefined)return item.name;if(imperial&&item.unit==="g")return (Math.round(n/28.35*10)/10)+" oz "+item.name;if(imperial&&item.unit==="ml")return (Math.round(n/236.6*10)/10)+" cups "+item.name;return (Math.round(n*10)/10)+(item.unit??"")+" "+item.name;};
const label=(e:Evidence)=>e==="from-video"?"From video":e==="estimated"?"Estimated":"Not stated";
const date=(day:number)=>"2026-10-"+String(day).padStart(2,"0");

export default function Prototype(){
  const keyboard=useKeyboard(); const [data,setData]=useState<Data>(load); const [route,setRoute]=useState<Route>("home"); const [id,setId]=useState("jollof"); const [query,setQuery]=useState(""); const [filter,setFilter]=useState("All"); const [favOnly,setFavOnly]=useState(false); const [capture,setCapture]=useState(false); const [picker,setPicker]=useState(false); const [servings,setServings]=useState(4); const [imperial,setImperial]=useState(false); const [checked,setChecked]=useState<string[]>([]); const [chosen,setChosen]=useState(date(6)); const [list,setList]=useState(false); const [draft,setDraft]=useState({title:"",sourceUrl:"",image:"",cuisine:"",ingredient:"",method:""}); const [errors,setErrors]=useState<string[]>([]);
  const update=(change:(current:Data)=>Data)=>setData(current=>{const next=change(current);localStorage.setItem(key,JSON.stringify(next));return next;});
  const recipe=data.recipes.find(x=>x.id===id)??data.recipes[0];
  const visible=useMemo(()=>data.recipes.filter(x=>(filter==="All"||x.category===filter)&&(!favOnly||x.favourite)&&(x.title+" "+x.cuisine).toLowerCase().includes(query.toLowerCase())),[data,filter,favOnly,query]);
  const go=(next:Route)=>{keyboard.hide();setRoute(next);};
  const open=(next:string)=>{setId(next);setServings(data.recipes.find(x=>x.id===next)?.servings??4);setChecked([]);go("recipe");};
  const toggle=(next:string)=>update(current=>({...current,recipes:current.recipes.map(x=>x.id===next?{...x,favourite:!x.favourite}:x)}));
  const save=()=>{const nextErrors=[!draft.title&&"A recipe title is required.",!draft.image&&"A dish image is required.",!draft.sourceUrl&&"An original recipe link is required.",!draft.ingredient&&"At least one ingredient is required."].filter(Boolean) as string[];if(nextErrors.length){setErrors(nextErrors);return;}const next:Recipe={id:crypto.randomUUID(),title:draft.title,image:draft.image,sourceUrl:draft.sourceUrl,cuisine:draft.cuisine||"Not stated",category:"Main",time:"30 min",servings:4,favourite:false,ingredients:[{id:crypto.randomUUID(),name:draft.ingredient,evidence:"from-video"}],method:draft.method.split("\\n").filter(Boolean)};update(current=>({...current,recipes:[next,...current.recipes]}));setId(next.id);setServings(4);setCapture(false);setDraft({title:"",sourceUrl:"",image:"",cuisine:"",ingredient:"",method:""});go("recipe");};
  const place=(day:string)=>{update(current=>current.mealPlan.some(x=>x.recipeId===recipe.id&&x.date===day)?current:{...current,mealPlan:[...current.mealPlan,{id:crypto.randomUUID(),recipeId:recipe.id,date:day} ]});setChosen(day);setPicker(false);go("plan");};
  const share=async()=>{const shareData={title:recipe.title,text:recipe.title+" — original source",url:recipe.sourceUrl};if(navigator.share)await navigator.share(shareData);else await navigator.clipboard.writeText(recipe.title+"\\n"+recipe.sourceUrl);};
  const nav=<nav className="bottom-nav" aria-label="Primary navigation"><button className={route==="home"?"active":""} onClick={()=>go("home")}>⌂<span>Home</span></button><button className={route==="cookbook"?"active":""} onClick={()=>go("cookbook")}>▦<span>Cookbook</span></button><button className="add-nav" onClick={()=>{keyboard.hide();setCapture(true)}} aria-label="Save a recipe"><PlusIcon/></button><button className={route==="plan"?"active":""} onClick={()=>go("plan")}>□<span>Plan</span></button><button onClick={()=>setFavOnly(x=>!x)}><HeartIcon/><span>Saved</span></button></nav>;
  const title=(name:string,action:React.ReactNode)=><header className="app-header"><div><img className="brand-lockup" src="/brand/savorly-logo.png" alt="Savorly"/><h1>{name}</h1></div>{action}</header>;
  const home=<main className="screen-content">{title("Your kitchen",<button className="primary small" onClick={()=>setCapture(true)}><PlusIcon/>Add recipe</button>)}<label className="search"><MagnifyingGlassIcon/><KeyboardInput aria-label="Search recipes" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search your recipes..."/></label><section className="category-grid">{["Main","Drink","Cake & Baking","Salad"].map(x=><button key={x} className={"category category-"+x.replaceAll(" ","-").replaceAll("&","and").toLowerCase()} onClick={()=>{setFilter(x);go("cookbook")}}><span>{x==="Main"?"Mains":x==="Drink"?"Drinks":x}</span></button>)}</section><div className="section-heading"><h2>Saved from video</h2><button onClick={()=>go("cookbook")}>See all<ChevronRightIcon/></button></div><button className="video-card" onClick={()=>open("jollof")}><img src={image.jollof} alt="Smoky Jollof Rice"/><div><p className="source"><PlayIcon/>From video</p><h3>Smoky Jollof Rice</h3><p>Ghanaian classic, made simple.</p><small>35 mins · 4 servings</small><span className="review">Review recipe<ChevronRightIcon/></span></div></button></main>;
  const cookbook=<main className="screen-content">{title("Your cookbook",<button className="coral-circle" onClick={()=>setCapture(true)} aria-label="Save a recipe"><PlusIcon/></button>)}<label className="search"><MagnifyingGlassIcon/><KeyboardInput aria-label="Search recipes" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search recipes"/></label><div className="filter-row">{["All","Main","Drink","Cake & Baking","Salad"].map(x=><button key={x} className={"chip "+(filter===x?"selected":"")} onClick={()=>setFilter(x)}>{x==="Main"?"Mains":x==="Drink"?"Drinks":x==="Cake & Baking"?"Cakes":x}</button>)}</div><div className="sort-row"><span>{visible.length} recipes</span><button className={favOnly?"sort-active":""} onClick={()=>setFavOnly(x=>!x)}><HeartIcon/>Favourites</button></div><section className="recipe-grid">{visible.map(x=><article className="recipe-card" key={x.id}><button className="recipe-card-open" onClick={()=>open(x.id)}><img src={x.image} alt={x.title}/><strong>{x.title}</strong><small>{x.cuisine} · {x.category}</small></button><button className="heart" onClick={()=>toggle(x.id)} aria-label="Toggle favourite">{x.favourite?<HeartFilledIcon/>:<HeartIcon/>}</button></article>)}</section></main>;
  const detail=<main className="recipe-page"><img className="recipe-hero" src={recipe.image} alt={recipe.title}/><button className="round-action back" onClick={()=>go("cookbook")} aria-label="Back"><ArrowLeftIcon/></button><button className="round-action share" onClick={share} aria-label="Share recipe"><Share1Icon/></button><section className="recipe-sheet"><p className="eyebrow">{recipe.cuisine} · {recipe.category}</p><div className="title-row"><h1>{recipe.title}</h1><button className="unstyled favourite" onClick={()=>toggle(recipe.id)}>{recipe.favourite?<HeartFilledIcon/>:<HeartIcon/>}</button></div><p className="muted">Personal recipe. Review estimated details before cooking.</p><div className="quick-facts"><span>◷ {recipe.time}</span><span>◉ {recipe.servings} portions</span></div><a className="video-link" href={recipe.sourceUrl} target="_blank" rel="noreferrer"><PlayIcon/>Open original source<ChevronRightIcon/></a><div className="recipe-tools"><div><small>SERVINGS</small><div className="stepper"><button onClick={()=>setServings(x=>Math.max(1,x-1))}><MinusIcon/></button><strong>{servings}</strong><button onClick={()=>setServings(x=>x+1)}><PlusIcon/></button></div></div><div className="unit-toggle"><button className={!imperial?"selected":""} onClick={()=>setImperial(false)}>Metric</button><button className={imperial?"selected":""} onClick={()=>setImperial(true)}>Imperial</button></div></div><h2>Ingredients</h2><ul className="ingredients">{recipe.ingredients.map(x=><li key={x.id}><button className={"check "+(checked.includes(x.id)?"checked":"")} onClick={()=>setChecked(current=>current.includes(x.id)?current.filter(y=>y!==x.id):[...current,x.id])}>{checked.includes(x.id)&&<CheckIcon/>}</button><span>{quantity(x,recipe.servings,servings,imperial)}<em className={"evidence "+x.evidence}>{label(x.evidence)}</em></span></li>)}</ul><h2>Method</h2><ol className="method">{recipe.method.length?recipe.method.map((x,i)=><li key={i}>{x}</li>):<li>Not stated — edit this recipe to add a method.</li>}</ol><button className="primary full" onClick={()=>{keyboard.hide();setPicker(true)}}><PlusIcon/>Add to meal plan</button></section></main>;
  const days=[6,7,8,9,10,11,12];const entries=data.mealPlan.filter(x=>x.date===chosen);const shopping=entries.flatMap(x=>data.recipes.find(y=>y.id===x.recipeId)?.ingredients??[]);
  const planner=<main className="screen-content plan">{title("Meal plan",<button className="round-action" onClick={()=>setList(x=>!x)} aria-label="Shopping list">☷</button>)}<div className="week"><button>‹</button><strong>6 – 12 October</strong><button>›</button></div><section className="calendar" aria-label="Meal plan calendar"><div className="calendar-head">{["Mon","Tue","Wed","Thu","Fri","Sat","Sun"].map(x=><span key={x}>{x}</span>)}</div><div className="calendar-days">{days.map((x,i)=>{const day=date(x);const item=data.mealPlan.find(y=>y.date===day);return <button key={day} className={"calendar-day "+(chosen===day?"selected-day":"")} onClick={()=>setChosen(day)}><span>{x}</span>{item?<b>{data.recipes.find(y=>y.id===item.recipeId)?.title.split(" ")[0]}</b>:<i>+</i>}</button>})}</div></section><section className="plan-day"><p>{chosen}</p>{entries.length?entries.map(entry=>{const x=data.recipes.find(y=>y.id===entry.recipeId);return x?<div className="plan-recipe" key={entry.id}><img src={x.image} alt={x.title}/><div><strong>{x.title}</strong><small>{x.time} · {x.category}</small></div></div>:null}):<span className="muted">Nothing planned yet. Add a recipe from its detail page.</span>}</section><section className="shopping-list"><button className="section-toggle" onClick={()=>setList(x=>!x)}><h2>Shopping list</h2><ChevronRightIcon/></button>{list&&<ul>{shopping.length?shopping.map(x=><li key={x.id}><CheckIcon/>{x.quantity?String(x.quantity)+(x.unit??"")+" ":""}{x.name}</li>):<li className="muted">Choose a recipe first.</li>}</ul>}</section></main>;
  const form=<div className="capture-form"><p className="capture-intro">Turn a saved video into a recipe you can trust. Everything stays on this device.</p>{errors.length>0&&<ul className="form-errors">{errors.map(x=><li key={x}>{x}</li>)}</ul>}<label>Original recipe link<KeyboardInput value={draft.sourceUrl} placeholder="https://..." onChange={e=>setDraft(x=>({...x,sourceUrl:e.target.value}))}/></label><label>Dish image URL<KeyboardInput value={draft.image} placeholder="https://..." onChange={e=>setDraft(x=>({...x,image:e.target.value}))}/></label><label>Recipe title<KeyboardInput value={draft.title} placeholder="e.g. Weeknight jollof" onChange={e=>setDraft(x=>({...x,title:e.target.value}))}/></label><label>Cuisine<KeyboardInput value={draft.cuisine} placeholder="e.g. Ghanaian" onChange={e=>setDraft(x=>({...x,cuisine:e.target.value}))}/></label><label>First ingredient <small>From video</small><KeyboardInput value={draft.ingredient} placeholder="e.g. 400g rice" onChange={e=>setDraft(x=>({...x,ingredient:e.target.value}))}/></label><label>Method <small>One step per line</small><KeyboardTextarea value={draft.method} onChange={e=>setDraft(x=>({...x,method:e.target.value}))}/></label><button className="primary full" onClick={save}><CheckIcon/>Save recipe</button></div>;
  return <div className="savorly-app"><MobileScroll className="app-scroll">{route==="home"?home:route==="cookbook"?cookbook:route==="recipe"?detail:planner}</MobileScroll>{nav}<BottomSheet open={capture} onOpenChange={setCapture} title="Save a recipe" description="Offline and private." snap={0.85}>{form}</BottomSheet><BottomSheet open={picker} onOpenChange={setPicker} title="Choose a day" description={"Add "+recipe.title+" to your week."} snap={0.5}><div className="day-picker">{days.map(x=><button key={x} onClick={()=>place(date(x))} className={chosen===date(x)?"selected":""}><strong>{["Mon","Tue","Wed","Thu","Fri","Sat","Sun"][x-6]}</strong><span>{x}</span></button>)}</div></BottomSheet></div>;
}
